"""Added google_form_active column

Revision ID: 250207c201b0
Revises: 
Create Date: 2026-01-16 20:45:49.623401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250207c201b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_form_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('google_form_active')

    # ### end Alembic commands ###
