"""Add account_status field to User model

Revision ID: 30c55a7b1cdd
Revises: 7f2f95249844
Create Date: 2026-02-04 23:21:56.905870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c55a7b1cdd'
down_revision = '7f2f95249844'
branch_labels = None
depends_on = None


def upgrade():
    # Helper to check existing columns
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('user')]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'account_status' not in columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('account_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_status')

    # ### end Alembic commands ###
