"""Add webhook secrets

Revision ID: 4452c926d26e
Revises: 2f8a1c3b4d5e
Create Date: 2026-01-27 23:51:47.880489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4452c926d26e'
down_revision = '2f8a1c3b4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_secret', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['webhook_secret'])
        batch_op.drop_column('background_image')

    with op.batch_alter_table('form_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_response', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('webhook_secret')

    # ### end Alembic commands ###
