"""Add indexes to Participant model

Revision ID: 68b21e7d5fec
Revises: 250207c201b0
Create Date: 2026-01-18 10:03:18.554746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b21e7d5fec'
down_revision = '250207c201b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index('idx_participant_event', ['event_id'], unique=False)
        batch_op.create_index('idx_participant_status', ['registration_status'], unique=False)
        batch_op.create_index('idx_participant_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_user')
        batch_op.drop_index('idx_participant_status')
        batch_op.drop_index('idx_participant_event')

    # ### end Alembic commands ###
