"""Initial migration

Revision ID: 7f2f95249844
Revises: 
Create Date: 2026-01-31 11:39:13.285966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2f95249844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Helper to check existing columns
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [c['name'] for c in inspector.get_columns('participant')]

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        if 'facebook' in columns:
            batch_op.drop_column('facebook')
        if 'phone' in columns:
            batch_op.drop_column('phone')
        if 'discord' in columns:
            batch_op.drop_column('discord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
