"""Add discord_webhook_url to Event model

Revision ID: a59bb1478fc2
Revises: 68b21e7d5fec
Create Date: 2026-01-18 10:33:58.018113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59bb1478fc2'
down_revision = '68b21e7d5fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_webhook_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('discord_webhook_url')

    # ### end Alembic commands ###
