"""Add character_traits fields to Role

Revision ID: aa0e1450a788
Revises: e7f8g9h1i2j3
Create Date: 2026-03-01 17:34:33.031264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0e1450a788'
down_revision = 'e7f8g9h1i2j3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_traits_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('character_traits_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('character_traits_data')
        batch_op.drop_column('character_traits_status')

    # ### end Alembic commands ###
